s1 = "this is an example of a simple String"
s2 = "THIS is a simple String"
s3 = "this is an ‘example’ of a simple String "

print(s1.capitalize())
print(s2.capitalize())
print(s3.capitalize())
print("-------------------------")
print(s1.ﬁnd("an"))
print(s2.ﬁnd("an"))
print(s3.ﬁnd("an"))
print("-------------------------")
print(s1.ﬁnd("an", 20))
print(s2.ﬁnd("an", 20))
print(s3.ﬁnd("an", 20))
print("-------------------------")
print(s1.ﬁnd("an", 5, 20))
print(s2.ﬁnd("an", 5, 20))
print(s3.ﬁnd("an", 5, 20))
print("-------------------------")
print(s1.islower())
print(s2.islower())
print(s3.islower())
print("-------------------------")
print(s1.isupper())
print(s2.isupper())
print(s3.isupper())
print("-------------------------")
print(s1.lower())
print(s2.lower())
print(s3.lower())
print("-------------------------")
print(s1.upper())
print(s2.upper())
print(s3.upper())
print("-------------------------")
print(s1.split())
print(s2.split())
print(s3.split())
print("-------------------------")
print(s1.split(" "))
print(s2.split(" "))
print(s3.split(" "))
print("-------------------------")
print(s1.strip())
print(s2.strip())
print(s3.strip())
print("-------------------------")
print(s1.strip("t"))
print(s2.strip("t"))
print(s3.strip("t"))
print("-------------------------")
print(s1.startswith("this"))
print(s2.startswith("this"))
print(s3.startswith("this"))
print("-------------------------")
print(s1.endswith("example"))
print(s2.endswith("example"))
print(s3.endswith("example"))
print("-------------------------")
print(s1.replace("simple", "QWERT"))
print(s2.replace("simple", "QWERT"))
print(s3.replace("simple", "QWERT"))
print("-------------------------")
